In [0]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

sns.set()

In [0]:
# example data from Machine Learning A-Z course
# https://www.superdatascience.com/pages/machine-learning

In [0]:
import os

os.chdir(r'/content/drive/My Drive/Colab Notebooks/hands_on_machine_learning/hands_on_machine_learning/data_preprocessing')

In [5]:
df = pd.read_csv('data.csv')
df.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [0]:
X = df[['Country', 'Age', 'Salary']].values
y = df['Purchased'].values

### Missing Data

In [21]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
X[:, 1:] = imputer.fit_transform(X[:, 1:])
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

### Encoding

In [45]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()
X[:, 0] = label_encoder.fit_transform(X[:, 0])

label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [44]:
from sklearn.preprocessing import OneHotEncoder

one_hot_encoder = OneHotEncoder(handle_unknown='ignore')
X_ = one_hot_encoder.fit_transform(X[:, :1])
X = np.c_[X_.toarray(), X[:, 1:]]
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

### Spliting data sets

In [0]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)

### Feature Scaling

In [48]:
from sklearn.preprocessing import StandardScaler

std_scaller = StandardScaler()

X_train = std_scaller.fit_transform(X_train)
X_test = std_scaller.fit_transform(X_test)
X_train

array([[-0.8660254 , -0.63245553,  1.58113883, -0.14146557, -0.44504083],
       [-0.8660254 ,  1.58113883, -0.63245553, -1.13172457, -1.03441923],
       [ 1.15470054, -0.63245553, -0.63245553,  0.60122868,  0.48112522],
       [-0.8660254 , -0.63245553,  1.58113883, -1.50307169, -1.53960072],
       [ 1.15470054, -0.63245553, -0.63245553,  1.09635818,  1.07050362],
       [-0.8660254 ,  1.58113883, -0.63245553,  1.34392293,  1.40729128],
       [ 1.15470054, -0.63245553, -0.63245553, -0.26524795,  0.06014065]])